name: Get YouTube Link (MacOS Bypass)

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Masukkan URL Video YouTube'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  get_link:
    # KUNCI RAHASIANYA DI SINI: Menggunakan server Mac untuk menghindari blokir IP Azure
    runs-on: macos-latest 

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install yt-dlp (Nightly Build)
      run: |
        python3 -m pip install --upgrade pip
        pip install -U --pre yt-dlp

    - name: Print Direct Link to Log
      run: |
        URL="${{ github.event.inputs.video_url }}"
        
        echo "=================================================="
        echo "MENCOBA BYPASS DARI SERVER MACOS..."
        echo "=================================================="
        
        # Perintah -g untuk mengambil link URL mentah (kualitas standar gabungan video+audio)
        yt-dlp --extractor-args youtube:player_client=tvhtml5,web --no-warnings -f "b" -g "$URL"
        
        echo "=================================================="
        echo "Jika link muncul di atas, segera salin dan gunakan!"
