name: Get YouTube Direct Link

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Masukkan URL Video YouTube'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      format_choice:
        description: 'Pilih tipe link yang ingin diambil:'
        required: true
        default: 'b'
        type: choice
        options:
          - 'b' # Kualitas standar (Video + Audio gabung, max 720p)
          - 'bestvideo' # Kualitas HD (Hanya Video, tanpa suara)
          - 'bestaudio' # Hanya Suara (Audio murni)

jobs:
  get_link:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install yt-dlp (Nightly Build)
      run: |
        python3 -m pip install --upgrade pip
        pip install -U --pre yt-dlp

    - name: Print Direct Link to Log
      run: |
        URL="${{ github.event.inputs.video_url }}"
        FORMAT="${{ github.event.inputs.format_choice }}"
        
        echo "=================================================="
        echo "BERIKUT ADALAH DIRECT LINK KAMU:"
        echo "=================================================="
        
        # Perintah -g digunakan untuk hanya mengambil URL mentah
        yt-dlp --extractor-args youtube:player_client=tvhtml5,web --no-warnings -f "$FORMAT" -g "$URL"
        
        echo "=================================================="
        echo "Link di atas memiliki masa kadaluarsa (expired). Segera gunakan!"
